# From https://github.com/concourse/concourse-docker/blob/master/docker-compose.yml
version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    networks:
      - concourse-network      
    environment:
      - POSTGRESQL_DATABASE=bitnami_concourse
      - POSTGRESQL_USERNAME=bn_concourse
      - POSTGRESQL_PASSWORD=bitnami1
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  concourse:
    image: concourse/concourse
    container_name: concourse
    command:  web --encryption-key 63FAF00A63FAF00A63FAF00A63FAF00A
    ports: ["8090:8080"]
    networks:
      - concourse-network
      - reverse-proxy
    environment:
      - CONCOURSE_POSTGRES_HOST=postgresql
      - CONCOURSE_POSTGRES_DATABASE=bitnami_concourse
      - CONCOURSE_POSTGRES_USER=bn_concourse
      - CONCOURSE_POSTGRES_PASSWORD=bitnami1
      - CONCOURSE_EXTERNAL_URL=http://embeddedstory.com:8090/
      - CONCOURSE_ADD_LOCAL_USER=diego:123
      - CONCOURSE_MAIN_TEAM_LOCAL_USER=diego
      - CONCOURSE_SESSION_SIGNING_KEY=/keys/session_signing_key
      - CONCOURSE_TSA_HOST_KEY=/keys/tsa_host_key
      - CONCOURSE_TSA_AUTHORIZED_KEYS=/keys/authorized_worker_keys
      - CONCOURSE_CLUSTER_NAME=EmbeddedStory
    volumes:
      - 'concourse_web_data:/bitnami/concourse'
      - './:/keys'

  concourse_worker:
    image: concourse/concourse
    command:  worker --runtime containerd
    privileged: true
    networks:
      - concourse-network      
    environment:
      - CONCOURSE_TSA_HOST=concourse:2222
      - CONCOURSE_TSA_PUBLIC_KEY=/keys/tsa_host_key.pub
      - CONCOURSE_TSA_WORKER_PRIVATE_KEY=/keys/worker_key
      # CONCOURSE_BIND_IP=0.0.0.0
      # CONCOURSE_BAGGAGECLAIM_BIND_IP=0.0.0.0
      # CONCOURSE_BAGGAGECLAIM_DRIVER=overlay
      - CONCOURSE_CONTAINERD_DNS_PROXY_ENABLE=true
      # CONCOURSE_WEB_PUBLIC_DIR=/opt/bitnami/concourse/web/public
      # CONCOURSE_WORK_DIR=/opt/bitnami/concourse
      # CONCOURSE_WORKER_TSA_WORKER_PRIVATE_KEY=a
    volumes:
      - './:/keys'

volumes:
  postgresql_data:
    driver: local
  concourse_web_data:
    driver: local

networks:
    reverse-proxy:
       external: true
    concourse-network:
       external: true
