theme: dark

server:
  host: 0.0.0.0
  port: 9091

totp:
  issuer: auth.embeddedstory.xyz

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    # Allow API calls
    - domain: cal.embeddedstory.xyz
      resources:
        - ".*/api.*"
      policy: bypass
    - domain: cal.embeddedstory.xyz
      policy: two_factor
    - domain: knw.embeddedstory.xyz
      policy: two_factor
    - domain: wiki.embeddedstory.xyz
      policy: two_factor
    - domain: main.embeddedstory.xyz
      policy: two_factor

session:
  name: authelia_session
  expiration: 3600  # 1 hour
  inactivity: 3600  # 1 hour
  domain: embeddedstory.xyz 

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:
  disable_startup_check: false
  filesystem:
    filename: /config/notification.txt
