version: "2"
services:

  bitwarden:
    image: vaultwarden/server:alpine
    container_name: bitwarden
    restart: unless-stopped
    environment:
      - WEBSOCKET_ENABLED=true
    volumes:
      - data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.bitwarden-ui.entrypoints=websecure
      - traefik.http.routers.bitwarden-ui.rule=Host(`bw.embeddedstory.xyz`)
      - traefik.http.routers.bitwarden-ui.service=bitwarden-ui
      - traefik.http.routers.bitwarden-ui.tls.certresolver=letsencryptresolver
      - traefik.http.services.bitwarden-ui.loadbalancer.server.port=80
      - traefik.http.routers.bitwarden-websocket.entrypoints=websecure
      - traefik.http.routers.bitwarden-websocket.tls.certresolver=letsencryptresolver
      - traefik.http.routers.bitwarden-websocket.service=bitwarden-websocket
      - traefik.http.routers.bitwarden-websocket.rule=Host(`bw.embeddedstory.xyz`) && Path(`/notifications/hub`)
      - traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012
    networks:
      - reverse-proxy

volumes:
  data:

networks:
  reverse-proxy:
    external: true
