---
- name: Deploy Traefik with Authelia 
  hosts: myembedded
  gather_facts: no
  tasks:
     - name: Make sure the folder exists 
       shell:
         cmd: |
           mkdir -p /srv/www/com.embeddedstory.router
           mkdir -p /srv/www/com.embeddedstory.router/config

     - name: Stop container 
       shell:
         cmd: |
           docker-compose down || exit 0
         chdir: /srv/www/com.embeddedstory.router

     - name: Download latest repo
       ansible.builtin.git:
         repo: git@github.com:EmbeddedStory/EasyVPS.git
         dest: /tmp/latestrepo 
         depth: 1
         version: myembedded 
         force: yes

     - name: Replace files of interest 
       become: yes
       shell:
          cmd: |
            mv /tmp/latestrepo/com.embeddedstory.router/docker-compose.yml docker-compose.yml
            mv /tmp/latestrepo/com.embeddedstory.router/configuration.yml config/configuration.yml
            mv /tmp/latestrepo/com.embeddedstory.router/users_database.yml config/users_database.yml
            sudo chmod -R 0600 secrets
            docker-compose up -d
          chdir: /srv/www/com.embeddedstory.router
