---
- name: Deploy Tiddly Wiki 
  hosts: myembedded
  gather_facts: no
  tasks:
     - name: Make sure the folder exists 
       shell:
         cmd: |
           mkdir -p /srv/www/xyz.myembedded.knw

     - name: Stop container 
       shell:
         cmd: |
           docker-compose down || exit 0
         chdir: /srv/www/xyz.myembedded.knw

     - name: Download latest repo
       ansible.builtin.git:
         repo: git@github.com:Dlozanof/web-services.git
         dest: /tmp/latestrepo 
         depth: 1
         version: feature/ansible
         force: yes

     - name: Replace files of interest 
       shell:
         cmd: |
           rm -f /srv/www/xyz.myembedded.knw/docker-compose.yml
           mv /tmp/latestrepo/xyz.myembedded.knw/docker-compose.yml /srv/www/xyz.myembedded.knw/docker-compose.yml
           docker-compose up -d
         chdir: /srv/www/xyz.myembedded.knw
