# Description
This is your typical tiddly wiki setup. It only needs two options, the user and password.
They are feeded via a .env file as shown in the docker compose file.

version: "2"
services:
  tiddlywiki:
    image: mazzolino/tiddlywiki
    env_file: .env
    environment:
      - PASSWORD=$PASSWORD
      - USERNAME=$USERNAME
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tiddlywiki.rule=Host(`knw.embeddedstory.xyz`)"
      - "traefik.http.routers.tiddlywiki.entrypoints=websecure"
      - "traefik.http.routers.tiddlywiki.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.tiddlywiki.middlewares=authelia@docker"
    container_name: tiddlywiki
    volumes:
      - ./data:/var/lib/tiddlywiki
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true